### ISSUE TITLE
chat/presence scope

### ISSUE THREAD

**Issue by UncleGoogle** [ppy/osu-web#5989]
Hi, 

Currently in docs there scopes:
`identify friends.read users.read`

but looks like there is something more for chat.

For example:
https://osu.ppy.sh/api/v2/chat/presence gives me:

```
{
    "error": "Invalid scope(s) provided."
}
```

Is is available for public use already?

**Comment by aspriddell** [comment]
no - only osu!lazer can access that if i'm not mistaken

the scopes are likely to change soon anyway, and there'll be more endpoints for public use (see #5981)

**Comment by UncleGoogle** [comment]
Hi, thanks for answer. BTW: is there any chance to open osu desktop app without need for login e.i. passing token that can be replaced for osu!lazer full scope token?

**Comment by peppy** [comment]
you will need to setup your own server to pass-through connections for that purpose. we don't plan on adding a client auth API in the near future.

**Comment by peppy** [comment]
I'm going to close this issue as it should be resolved via #5981

**Comment by UncleGoogle** [comment]
> setup your own server to pass-through connections for that purpose
Do you mean something like this? https://www.reddit.com/r/Diablo/comments/kj4fn/how_bypass_login_and_to_get_to_the/

**Comment by peppy** [comment]
If you are making an application or service, the users should be authenticating with you, and any requests to the API would be done via your server.

I get that this takes a bit more effort to implement, but that's all we are geared to handle for now.

**Comment by UncleGoogle** [comment]
I've already setup simple server for exchanging `code` and refreshing tokens: https://github.com/UncleGoogle/galaxy-integration-osu-auth/blob/master/app.py

Still don't understand how it relates to bypassing authentication to desktop app.

**Comment by peppy** [comment]
Sorry maybe I misunderstood your original question in that case. I think what you may be wanting to do will not be possible, though.

**Comment by UncleGoogle** [comment]
You probably answer to OP, and I though you answered:

> BTW: is there any chance to open osu desktop app without need for login e.i. passing token that can be replaced for osu!lazer full scope token?

So this ^ side question is impossible, thanks for clarification.

And for chat I will ask again when Galaxy will support chat, as it is `coming soon`. Maybe not in this year though.

**Comment by cl8n** [comment]
> we don't plan on adding a client auth API in the near future

what's the reason for waiting? third-party native apps could make use of PKCE, and client credentials grant would be useful for automated or one-off requests on behalf of the client owner (like apiv1)

I've seen people recommend abusing the lazer secret in absence of client credential grants already, so I think this should be a priority if there's not an equally important reason for holding it off.

**Comment by peppy** [comment]
Because it open a whole new can of worms which I do not want to deal with (having thousands of end users hitting API at varying rates, making rate limiting single applications very hard, as one example). It's not just an "on" switch without maintenance issues.

Abuse of secret key will likely result in 100% bans to all users *and* consumers so I would recommend against that. End user applications are not something we have supported with api v1 and not something we will support (yet) with v2.
