### ISSUE TITLE
Incorrect displaying of "non-calculated scores"

### ISSUE THREAD

**Issue by DJMakerMusician** [ppy/osu-web#9219]
When playing in lazer, some scores take time to calculate, and I can see that in-game, but the web browser says, that only personal best scores can give pp.
![image](https://user-images.githubusercontent.com/73738591/185789920-e7b7f344-7c49-40b5-8349-9b3bdc168817.png)
![osu_2022-08-21_14-02-40](https://user-images.githubusercontent.com/73738591/185789935-7bf78c2d-062c-49c5-8b74-3789b5e00b6c.png)

**Comment by peppy** [comment]
They don't take time to calculate. If anything, the in-game one is likely wrong.

Needs further investigation.

**Comment by peppy** [comment]
@nanaya Able to check on this? The pp values do seem to be populating correctly.

```sql
root@db-master:osu> select * from solo_scores_performance where score_id = 47472793;
| score_id | pp    |
|----------|-------|
| 47472793 | 12.76 |
1 row in set
```

![11FAF0E7-B82E-4221-ACE9-7403CCBC7DAC](https://user-images.githubusercontent.com/191335/188296052-2e858b30-b054-4c91-b1b8-b22e737e75c4.jpeg)

**Comment by nanaya** [comment]
score displayed on the web is from osu_scores which for lazer is converted when the score is submitted and thus won't have the pp value

**Comment by peppy** [comment]
Hmmmmmmm I see. Did we have something in place previously to make this work? I swear lazer score pp values were showing in recent.

I guess it's safe to say this is resolved with the new table format implicitly.

**Comment by peppy** [comment]
@nanaya with the change to `solo_scores`, do we have new messaging for the case that pp is not calculated yet? the message in this issue in particular will not be correct going forward, i believe. at least not with how things work currently (every lazer score does get pp calculated, unless a fail i believe).

**Comment by nanaya** [comment]
I haven't added it. Shouldn't be too difficult.

**Comment by Samaoo** [comment]
The bug is still present as far as I can tell.
<img width="960" alt="lazer" src="https://user-images.githubusercontent.com/26160742/193100701-8184a646-1706-4a7c-841a-28f401ebdf3a.png">
<img width="960" alt="web" src="https://user-images.githubusercontent.com/26160742/193100715-04cd2dfb-a020-44c4-b581-dbea2a1437d0.png">

**Comment by nanaya** [comment]
It's not fixable until the score storage system is switched to new one. If anything, the best tooltip it can currently give out is "pp value for score from lazer client isn't available on web at the moment" (or something along that line).

The fix in the related PR is for when the system is finally migrated.
